MessagingException: Add two new Event Ids
Added Event Ids:
- 38 - ConnectionToWebServiceFailed
- 39 - ConnectionToMessageBrokerFailed

These Event Ids are used to identify the logging event.